### ISSUE TITLE
Warning: Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by klutchell** [akhilerm/tag-push-action#367]
GitHub Actions workflows using this action now receive a warning that Node.js 16 actions are deprecated.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: akhilerm/tag-push-action. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by klutchell** [comment]
I just noticed that this has been [fixed in master](https://github.com/akhilerm/tag-push-action/commit/af4f7e0d566b3ebc1b3c6da1a14e88a14be2c9c5), there just isn't a GitHub Release with the fix yet.

**Comment by klutchell** [comment]
@akhilerm any plans to drop a new major release that includes the node20 change? I'm pinned to the commit for now.

**Comment by akhilerm** [comment]
I dont think it will need a new major release, as there is no major architecture change. The change from 1.x -> 2.x was when the backend copy feature was overhauled to use crane instead of  containerd. I will make a new minor version release. 

Thanks for looking into it.

**Comment by akhilerm** [comment]
New release https://github.com/akhilerm/tag-push-action/releases/tag/v2.2.0 has been made and supports nodejs 20
